### PR TITLE
on load new suggestion/version, recheck checkboxes.

### PR DESCRIPTION
**Pull request by mmou**

### CODE REVIEW

**Comment by mmou** [comment]
this is the only obvious bug i notice with grid/groundline.

**Comment by bqpd** [comment]
Already work for me in current master, @mmou, does it work for you?

**Comment by mmou** [comment]
......okay it does now.... :|

**Comment by bqpd** [comment]
Sorry, I think there was a midair commit collision! :p Eeway fixed this and I pushed belatedly.

**Pull request closed without merging**
