### PR TITLE
add version history functionality

### PR DESCRIPTION
**Pull request by mmou**

### CODE REVIEW

**Comment by mmou** [comment]
todo:

where to put undo/redo?
make only 1 row of versions show up

disable saving when no actionQueue sketches
disable undo/redo buttons appropriately

make 'selecting a suggestion' an action also added to actionQueue.
check for other corner cases of undo/redo (especially how they work with version history).

make "move whole picture" another tool

**Comment by bqpd** [comment]
Oh man, this is exciting.

**Comment by olearym** [comment]
This looks good to me. Can we merge so I can make layout nice things happen?

**Comment by eewayhsu** [comment]
Yay :D let's do it

**Pull request merged**
